### ISSUE TITLE
Create useContractEvents hook

### ISSUE THREAD

**Issue by 0xEniotna** [apibara/starknet-react#207]
Hey, do you think it is a good idea to add Wagmi's `useContractEvent` hook ? https://wagmi.sh/react/hooks/useContractEvent

I'd live to use that for my project so I guess it could be the case for others as well !

As a junior dev I'm not sure how difficult it is to make the necessary changes to adapt this file [useContractEvent](https://github.com/wagmi-dev/wagmi/blob/main/packages/react/src/hooks/contracts/useContractEvent.ts) but I'd love to give it a try !

**Comment by fracek** [comment]
Yes, I think that would be a great idea! The main issue is that starknet.js provider doesn't support it because it defaults to the gateway provider. Until the ecosystem moves over to the json rpc provider I don't think it's possible to add this in a way that integrates with the rest of the library.

To go more in detail, the default provider is replaced with the wallet's provider once the user connects (so network changes with the user's wallet), so we cannot rely on the json rpc at all.

For your use case, you can manually instantiate a `RpcProvider` and use that in your code.

Keeping this issue open so in the future we can revisit this decision.

**Comment by Pet3ris** [comment]
Alchemy does have an events API and it seems fairly similar to TokenFlow? Could they be harmonized/supported?

**Comment by fracek** [comment]
For this to happen we need wallets to switch to the rpc provider. Once that happens, we can implement this issue.

**Comment by fracek** [comment]
Close in favour of #465
