### ISSUE TITLE
Make `starknet-react` hooks work with server side components

### ISSUE THREAD

**Issue by Pet3ris** [apibara/starknet-react#235]

**Comment by oboutarf** [comment]
Hello @Pet3ris, i would like to be assigned on this issue!

**Comment by fracek** [comment]
After thinking about this for a while, I believe Starknet React will not support server components by design. For server components, developers should use starknet.js directly. 

With Starknet React v2, we now share almost everything with starknet.js so it should be relatively easy to mix the 2 in a dapp.
