### ISSUE TITLE
Update `create-starknet` to use Starknet React v3

### ISSUE THREAD

**Issue by fracek** [apibara/starknet-react#481]
We have a `create-starknet` package to quickly initialize a Starknet project. It should be updated to Starknet React v3

**Tasks**

 - [ ] Update the package build system to be the same as the core package (tsup).
 - [ ] Update the template to create a project that uses Starknet React v3.

**Comment by EjembiEmmanuel** [comment]
@fracek I

**Comment by fracek** [comment]
Hello, you need to apply through onlydust.

**Comment by Blumebee** [comment]
Hi @EjembiEmmanuel, all applications must go through the ODHack hackathon page. All information are in the main telegram group or here: https://app.onlydust.com/hackathons/odhack-70 

Maintainers will be reviewing applications via the platform, not through the comments. Thanks for understanding and respecting this way!

**Comment by ikemHood** [comment]
Hey @Blumebee and @fracek I would like to work on this, but this issue doesn't seems to display for me on Onlydust

**Comment by Blumebee** [comment]
@ikemHood that is normal, all issues are to be displayed tomorrow on the hackathon page. Again I invite you to read the information in the [main telegram group](https://t.me/+Q1Oin_LMxpM0MTk8) or here: https://app.onlydust.com/hackathons/odhack-70

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community🇷.


### How I plan on tackling this issue
To update the create-starknet package to support Starknet React v3, I would take the following approach:

Understand the Current Setup
Review the existing create-starknet package structure, focusing on the build system and the template files it uses to generate new projects.
Identify the current build system 
Update Dependencies: Modify the template’s package.json to include the latest version of Starknet React v3 and any other relevant dependencies.

I would love to work on this

**Comment by BDCoy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
Hello, I’m Brayan. With over 3 years of experience in development, I am passionate about contributing to open-source projects and currently expanding my skill set with Rust, Cairo, and Solidity as part of my involvement with Dojo Coding. My recent role as a Full Stack Developer allowed me to specialize in a range of technologies including React, NextJs, Node.js, JavaScript, TypeScript, Docker, among many others. I am eager to apply my extensive experience and newly acquired skills to new challenges and innovative projects.

### How I plan on tackling this issue
1. I will update the build system to use tsup, aligning it with the core package. This involves configuring tsup to handle the build process, ensuring it compiles TypeScript files efficiently.

2. I will modify the template to create a project that uses Starknet React v3. This includes updating dependencies and ensuring compatibility with the latest version of Starknet React.

3. I will thoroughly test the updated package and template to ensure everything works as expected. This includes running the build process, initializing new projects, and verifying that the projects function correctly with Starknet React v3.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
As an experienced Full Stack Blockchain Developer, I'm excited to contribute my expertise to Edition 7 of the OnlyDust hackathons. With a strong background in Next.js, TypeScript, JavaScript, React, Node.js, Solidity, and Cairo, I've honed my technical skills across the blockchain development landscape.
My journey with OnlyDust began at Edition 2, and I've since made 28 contributions across 11 projects. This extensive experience on the platform has allowed me to develop a keen understanding of delivering high-quality solutions under tight deadlines. I bring a unique blend of technical prowess and user-centric design to every project, whether I'm crafting immersive 3D experiences or developing innovative smart contracts.
My track record demonstrates my ability to adapt quickly and contribute effectively to diverse challenges. I'm confident in my capacity to tackle new problems and drive innovation in the blockchain space. As we embark on Edition 7, I'm eager to leverage my hackathon experience and technical skills to push the boundaries of what's possible in blockchain development.
With a passion for creating cutting-edge solutions, I'm excited to collaborate with the OnlyDust community and contribute to the advancement of the blockchain ecosystem.


### How I plan on tackling this issue
To solve this issue, i would:

Update Build System
Replace the current build system with tsup, matching the core package.
Update package.json to include tsup as a dev dependency.
Create or modify the tsup configuration file (tsup.config.ts) to match the core package settings.
Update build scripts in package.json to use tsup.
Update Template for Starknet React v3
Review the current template structure and identify all areas that need updating.
Update dependencies in the template's package.json to include Starknet React v3 and its peer dependencies.
Modify React components to use the updated Starknet React v3 hooks and utilities.
Update any Starknet-specific configurations to align with v3 requirements.
Update CLI Tool
Modify the CLI tool to generate projects using the updated template.
Ensure that the CLI properly sets up the new project structure and dependencies.
Testing
Create test projects using the updated create-starknet package.
Verify that the generated projects successfully use Starknet React v3.
Test the build process of generated projects to ensure compatibility.
Documentation Updates
Update the README of the create-starknet package to reflect the changes.
Modify any usage instructions or examples to align with Starknet React v3.
Version Bump and Release
Update the package version in package.json.
Create a changelog detailing the updates and improvements.
Prepare the package for release on npm.
Compatibility Check
Ensure the updated package is compatible with the latest Starknet tooling and libraries.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, and Solidity. My journey with OnlyDust hackathons began at Edition 1, and I've since made 47 contributions across 11 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure.
I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges.
As we surf through Edition 7, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue

I will update the `create-starknet` package to initialize Starknet projects using Starknet React v3 and align its build system with the core package:

1. **Review and Plan**:
   I will examine the current package structure and identify necessary updates.

2. **Update Build System**:
   I will implement tsup as the new build system, matching the core package configuration.

3. **Update Template**:
   I will modify the project template to use Starknet React v3, updating components, hooks, and dependencies.

4. **Revise Scripts**:
   I will update initialization scripts to reflect template changes and ensure correct dependency installation.

5. **Testing**:
   I will thoroughly test the updated package across different environments and scenarios.

6. **Documentation**:
   I will update all relevant documentation to reflect the changes and new features.

7. **Version and Changelog**:
   I will bump the package version and update the changelog accordingly.

8. **CI/CD Updates**:
   I will adjust CI/CD pipelines to accommodate the new build system.

9. **Release Preparation**:
   I will create a detailed pull request and be ready to address feedback.

10. **Post-Release**:
    I will update external references and monitor initial user feedback.

This approach ensures a comprehensive update of the `create-starknet` package, aligning it with Starknet React v3 and improving its build process.

**Comment by Samuel1-ona** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
Hello, I'm Samuel, a Cairo developer and smart contract researcher with experience in frontend development using React. Currently, I'm working on Coiton, a platform for real estate trading.

### How I plan on tackling this issue
How I Plan on Tackling This Issue
Update the Build System to Use tsup:
I will replace the existing build system with tsup to align with the core package. This involves configuring tsup to handle TypeScript compilation, bundling, and generating declaration files. The tsup configuration will be tailored to optimize build performance while ensuring compatibility with both CommonJS and ESModules formats.

Modify the Template to Support Starknet React v3:
I will update the project template to use Starknet React v3, which includes revising dependencies in package.json and refactoring the template codebase to leverage the latest API features and conventions introduced in v3. Special attention will be given to addressing any breaking changes from previous versions, ensuring seamless integration.

Comprehensive Testing:
Post-modification, I will conduct thorough testing of the package. This includes:
Running the tsup build process to verify successful compilation and bundling.
Initializing new projects using the updated template to ensure that all configurations are correctly applied.
Testing the functionality of generated projects, specifically focusing on their interaction with Starknet React v3 to confirm full compatibility.
Any issues discovered during testing will be promptly addressed to guarantee the robustness of the package.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I have experience with frontend development and blockchain integration, particularly with Starknet and React. I can leverage this background to efficiently update the `create-starknet` package by aligning the build system with `tsup` and integrating Starknet React v3 into the project template, ensuring compatibility and a streamlined setup process.

### How I plan on tackling this issue
To update the `create-starknet` package for Starknet React v3:

1. **Update Build System:** Migrate the package build system to use `tsup`, aligning it with the core package’s setup.
2. **Update Template:** Modify the project template to integrate Starknet React v3, ensuring it sets up a new project with the latest version and dependencies.

**Comment by Luluameh** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I am a frontend developer with extensive experience in React.js , utilizing TypeScript to build dynamic and responsive user interfaces. My background in these technologies allows me to create seamless and efficient web applications, focusing on delivering a user-friendly experience. By combining my technical skills with a strong understanding of modern development practices, I am well-equipped to contribute to any project, ensuring that the final product is both high-performing and intuitive for end-users.

### How I plan on tackling this issue
To effectively approach a problem, I would follow a systematic process:
Understand the Problem:
Begin by fully understanding the problem statement. I would identify the key requirements, constraints, and goals to ensure I’m addressing the right issue.
Research and Analysis:

Conduct thorough research to explore existing solutions or similar problems. Analyze different approaches to determine the most effective solution that aligns with the project’s needs.
Break Down the Problem:

Decompose the problem into smaller, manageable tasks. This helps in tackling each aspect individually and ensures that no critical details are overlooked.
Plan and Strategize:

Develop a detailed plan of action, including the technologies, tools, and methods that will be used. I would prioritize tasks based on their importance and dependencies.
Implement the Solution:
Begin coding or applying the solution step by step, adhering to best practices and coding standards. I would continuously test the solution during implementation to catch and resolve issues early.
Testing and Validation:
After implementation, I would rigorously test the solution across different scenarios and environments. This includes both unit testing and user acceptance testing to ensure the solution is robust and meets all requirements.
Review and Optimize:
Evaluate the solution to identify any areas for improvement or optimization. This might involve refining the code, improving performance, or enhancing the user experience.
Documentation and Knowledge Sharing:

**Comment by HumbertoTM10** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-react).

### My background and how it can be leveraged
I'm a software developer with experience working with React in Web2 projects, I'm getting more into the Web3 world and will be pleased to contribute in the project.

### How I plan on tackling this issue
First, I will review the create-starknet package structure, so I can analize the current build system so I can correctly modify the package.json to include the latest version of Starknet React v3 as well as any other respective changes.

**Comment by fracek** [comment]
Hey @BDCoy have a go at the issue.

**Comment by BDCoy** [comment]
Thanks I'll start working right now

**Comment by BDCoy** [comment]
Hi @fracek,

I’ve just opened the PR. Could you please review the solution description to ensure the issue was addressed correctly?
